##################### Common Packages #######################
############################################################
- name: Install common packages
  hosts: all
  remote_user: ubuntu
  
  tasks:
    - name: install nfs-common
      become: true
      apt:
        pkg:
        - nfs-common
        update_cache: yes
        state: latest
    - name: install python-docker
      become: true
      apt:
        pkg:
        - python3-docker
        update_cache: yes
        state: latest
      tags:
        - python-docker