- name: enable ipv6 on all hosts
  hosts: all
  remote_user: ubuntu
  
  tasks:
    # Remove ipv6 disable entries from /etc/sysctl.conf
    - name: Enable IPv6 with sysctl
      become: true
      ansible.posix.sysctl:
        name: "{{ item }}"
        state: "absent"
        reload: "yes"
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6