# Default values for rust-server-helm
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: rustdesk-server

image:
  repository: rustdesk/rustdesk-server
  pullPolicy: IfNotPresent
  tag: "1.1.10-3"

url: rustdesk-server.local

hbbs:
  replicaCount: 1
  ressources:
    limits:
      cpu: 1
      memory: 1024Mi

service:
  type: LoadBalancer

data:
  storage: 1Gi
  storageClassName: managed-nfs-storage

hbbr:
  replicaCount: 1
  ressources:
    limits:
      cpu: 1
      memory: 1024Mi