---
apiVersion: v1
kind: Secret
metadata:
  name: couchdb-credentials
  namespace: couchdb
type: Opaque
stringData:
  adminUsername: "${COUCHDB_USER}"
  adminPassword: "${COUCHDB_PASSWORD}"
  cookieAuthSecret: "${COUCHDB_COOKIE_AUTH_SECRET}"
  erlangCookie: "${COUCHDB_ERLANG_COOKIE}"
